name: GitHub Profile Summary Cards

on:
  schedule: # Run once daily
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 5.5 # for IST (India time)
          EXCLUDE: ""
          AUTO_PUSH: true
